sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu:trusty

script:
  - docker run --rm -v $(pwd)/:/build/ -w /build/ nxos/nxos bash build.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh -O u.sh
      - chmod a+x ./u.sh
      - ./u.sh release/*
    on:
      branch: master
