language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - echo "BEFORE_INSTALL"

install:  
  - echo "INSTALL"

script:
  - chmod a+x ./build.sh
  - echo "SCRIPT"
  - ./build.sh

after_success:
  - echo "AFTER SUCCESS"
